#!/bin/sh
#
# Gets file list on standard input and RPM_BUILD_ROOT as first parameter
# and searches for omitted files (not counting directories).
# Returns it's output on standard output.
#
# filon@pld.org.pl

RPM_BUILD_ROOT=$1

if [ ! -d "$RPM_BUILD_ROOT" ] ; then
	cat > /dev/null
	exit 1
fi

[ "$TMPDIR" ] || TMPDIR=/tmp
FILES_DISK=`mktemp $TMPDIR/rpmXXXXXX`
FILES_RPM=`mktemp $TMPDIR/rpmXXXXXX`

find $RPM_BUILD_ROOT -type f -o -type l | LC_ALL=C sort > $FILES_DISK
LC_ALL=C sort > $FILES_RPM

diff -d "$FILES_DISK" "$FILES_RPM" | grep "^< " | cut -c3- | 
while read f; do
	if test "$RPM_BUILD_ROOT/usr/share/info/dir" != "$f" ; then
		echo $f | sed -e "s#^$RPM_BUILD_ROOT#   #g"
	fi
done

rm -f $FILES_DISK
rm -f $FILES_RPM
